"""FIN 580 Final Project — Demo Dashboard (single-page, story-driven).

Walk-through-style dashboard for a classroom demo. Scroll top to bottom — each
section answers one question. Sidebar has shortcut links.

Run:    streamlit run dashboard/app.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path

# Make the fin580 package importable when streamlit runs from inside dashboard/
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

RUNS_DIR = ROOT / "runs"
PHASE1_OUTPUT = ROOT / "phase1" / "output"

# Per-window run dirs across 2019-2024 — canonical 25-pad / all-OpenAI
# Strategy 1 ledger after the Agent-1 trailing-baseline cache fix. Section 6
# (baselines vs S2-S10) restricts to 2024 only because the deterministic
# baselines were run on 2024.
HEADLINE_RUN = RUNS_DIR / "2026-05-05-strategy1-2024Q1_2024Q4-target-realsar-v2_5_fix"
WINDOW_RUNS = {
    "2019":  RUNS_DIR / "2026-05-05-strategy1-2019Q1_2019Q4-target-realsar-v2_5_fix",
    "2020":  RUNS_DIR / "2026-05-05-strategy1-2020Q1_2020Q4-target-realsar-v2_5_fix",
    "2021":  RUNS_DIR / "2026-05-05-strategy1-2021Q1_2021Q4-target-realsar-v2_5_fix",
    "2022":  RUNS_DIR / "2026-05-05-strategy1-2022Q1_2022Q4-target-realsar-v2_5_fix",
    "2023":  RUNS_DIR / "2026-05-05-strategy1-2023Q1_2023Q4-target-realsar-v2_5_fix",
    "2024":  HEADLINE_RUN,
}


def _window_for_fpe(fpe: str) -> str:
    y = int(fpe[:4])
    if y == 2019: return "2019"
    if y == 2020: return "2020"
    if y == 2021: return "2021"
    if y == 2022: return "2022"
    if y == 2023: return "2023"
    return "2024"


def _run_dir_for_fpe(fpe: str) -> Path:
    return WINDOW_RUNS[_window_for_fpe(fpe)]

st.set_page_config(
    page_title="FIN 580 — Multi-Agent Permian Trading Demo",
    page_icon="🛰️",
    layout="wide",
)

# -----------------------------------------------------------------------------
# Sidebar (just navigation hints)
# -----------------------------------------------------------------------------
st.sidebar.title("FIN 580 Final Demo")
st.sidebar.markdown(
    "Scroll the page top → bottom to follow the story. "
    "Or jump to a section:"
)
st.sidebar.markdown(
    """
    - [1. The Question](#section-1)
    - [2. Real Data the System Reads](#section-2)
    - [3. The 5 Agents](#section-3)
    - [4. Worked Example: FANG 2024-Q2](#section-4)
    - [5. All Long Trades](#section-5)
    - [6. Comparison vs Baselines](#section-6)
    - [7. Honest Limitations](#section-7)
    """
)

# -----------------------------------------------------------------------------
# Cached loaders
# -----------------------------------------------------------------------------
@st.cache_data
def load_all_cells():
    """Cell results across all six yearly windows, deduped (last attempt wins)."""
    parts = []
    seen: set[Path] = set()
    for run in WINDOW_RUNS.values():
        if run in seen:
            continue
        seen.add(run)
        p = run / "strategy_01" / "cell_results.parquet"
        if not p.exists():
            continue
        df = pd.read_parquet(p).drop_duplicates(
            subset=["ticker", "fiscal_quarter_end"], keep="last"
        )
        df["window"] = df["fiscal_quarter_end"].apply(_window_for_fpe)
        parts.append(df)
    return pd.concat(parts, ignore_index=True) if parts else pd.DataFrame()


@st.cache_data
def load_cell_results():
    """Headline 2024 cells only — kept for Section 6 baseline-vs-S1 comparison."""
    p = HEADLINE_RUN / "strategy_01" / "cell_results.parquet"
    return pd.read_parquet(p) if p.exists() else pd.DataFrame()


@st.cache_data
def load_all_trades():
    """Per-trade P&L across all 6 yearly windows.

    Primary path: read the canonical trade ledger from
    runs/inference/strategy01_trades.csv (in git, regenerated by
    `python -m fin580.inference.build_evidence_pack`). This lets a
    fresh collaborator render the dashboard without WRDS-licensed CRSP
    data on disk.

    Fallback path: if the CSV is missing, recompute from CRSP +
    earnings dates (the original behaviour, useful when iterating on
    new run dirs before regenerating the rollup).
    """
    csv_path = RUNS_DIR / "inference" / "strategy01_trades.csv"
    if csv_path.exists():
        df = pd.read_csv(csv_path)
        if len(df) and "fiscal_quarter_end" in df.columns:
            df["window"] = df["fiscal_quarter_end"].apply(_window_for_fpe)
            return df

    from fin580.backtest.pnl_engine import compute_trade_pnl
    from fin580.data.crsp_loader import load_combined, price_at
    from fin580.inference.pnl import _earnings_dates, _exit_price

    try:
        crsp = load_combined()
    except FileNotFoundError:
        # CRSP CSVs are WRDS-licensed and gitignored. Without them and
        # without the cached strategy01_trades.csv, we cannot construct
        # the trade ledger. Return an empty frame and let the calling
        # sections surface a clear "trade ledger missing" warning.
        return pd.DataFrame()
    eds = _earnings_dates()
    cells = load_all_cells()
    if cells.empty:
        return pd.DataFrame()
    longs = cells[cells["decision"] == "long"]
    rows = []
    for _, r in longs.iterrows():
        ticker = r["ticker"]
        fpe_str = r["fiscal_quarter_end"]
        fpe = datetime.strptime(fpe_str, "%Y-%m-%d").date()
        T = datetime.strptime(r["decision_date_T"], "%Y-%m-%d").date()
        size = float(r.get("final_size_pct", 0.10))
        ed = eds.get((ticker, fpe))
        if ed is None:
            continue
        series = crsp.get(ticker, [])
        if not series:
            continue
        entry_p = price_at(series, T)
        exit_p = _exit_price(series, ed, days_after=2)
        if entry_p is None or exit_p is None:
            continue
        pnl = compute_trade_pnl(
            entry_price=entry_p, exit_price=exit_p, size_pct=size,
            capital_usd=1_000_000, cost_bps=30,
        )
        rows.append({
            "window": _window_for_fpe(fpe_str),
            "strategy": 1,
            "ticker": ticker,
            "fiscal_quarter_end": fpe_str,
            "entry_date_T": T.isoformat(),
            "exit_date": (ed + timedelta(days=2)).isoformat(),
            "entry_price": entry_p,
            "exit_price": exit_p,
            "size_pct": size,
            "gross_return_pct": pnl["gross_return_pct"],
            "net_return_pct": pnl["net_return_pct"],
            "gross_pnl_usd": pnl["gross_pnl_usd"],
            "net_pnl_usd": pnl["net_pnl_usd"],
        })
    return pd.DataFrame(rows)


@st.cache_data
def load_strategy1_trades():
    """Headline 2024 trades only (used by Section 6 baseline chart)."""
    p = RUNS_DIR / "inference" / "strategy01_trades_2024.csv"
    return pd.read_csv(p) if p.exists() else pd.DataFrame()


@st.cache_data
def load_headline_table():
    p = RUNS_DIR / "inference" / "headline_table_2024.csv"
    return pd.read_csv(p) if p.exists() else pd.DataFrame()


@st.cache_data
def load_evidence_pack():
    p = RUNS_DIR / "inference" / "evidence_pack.json"
    return json.loads(p.read_text()) if p.exists() else {}


@st.cache_data
def load_benchmark_prices():
    """Daily close prices for XES (oil & gas equipment ETF) and VOO (S&P 500 ETF)
    pre-fetched from yfinance, persisted in phase1/output/benchmark_prices.csv."""
    p = PHASE1_OUTPUT / "benchmark_prices.csv"
    if not p.exists():
        return pd.DataFrame()
    df = pd.read_csv(p)
    df["date"] = pd.to_datetime(df["date"])
    return df.sort_values("date").reset_index(drop=True)


def load_agent_json(ticker: str, fpe: str, agent: str) -> dict | None:
    """Look up an agent JSON from the run dir matching the cell's fiscal year."""
    run = _run_dir_for_fpe(fpe)
    p = run / "strategy_01" / "agent_outputs" / f"{ticker}_{fpe}_{agent}.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def load_sar_aggregate(ticker: str, fpe: str, T: str):
    p = (
        PHASE1_OUTPUT
        / "sentinel1_cache"
        / "firm_quarter_aggregates"
        / f"{ticker}_{fpe}_{T}_n25.json"
    )
    return json.loads(p.read_text()) if p.exists() else None


# =============================================================================
# Title block
# =============================================================================
st.title("🛰️ Multi-Agent Permian Trading System")
st.caption("FIN 580 Final Project — End-to-End Demo with Real Sentinel-1 SAR (2019-2024)")

# Top-level scoreboard
all_trades = load_all_trades()
all_cells = load_all_cells()
trades = load_strategy1_trades()  # 2024-only ledger (Section 6 baseline chart)
cells = load_cell_results()       # 2024-only cells (Section 6)
ev_pack = load_evidence_pack()

c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("Window", "2019 → 2024")
c2.metric("Cells evaluated", f"{len(all_cells)}")
c3.metric("Long trades fired", f"{len(all_trades)}")
if len(all_trades):
    wins_6y = (all_trades.net_return_pct > 0).sum()
    c4.metric("Hit rate", f"{wins_6y/len(all_trades):.0%}")
    c5.metric(
        "Mean net return",
        f"{all_trades.net_return_pct.mean()*100:+.2f}%",
    )

# Per-window mini breakdown
if len(all_trades):
    breakdown = all_trades.groupby("window").agg(
        cells=("ticker", "count"),
        wins=("net_return_pct", lambda s: (s > 0).sum()),
        total_pnl=("net_pnl_usd", "sum"),
    )
    # add cell counts per window from all_cells
    cell_counts = all_cells.groupby("window").size()
    breakdown["cells_total"] = cell_counts
    cols = st.columns(len(WINDOW_RUNS))
    for col, label in zip(cols, WINDOW_RUNS.keys()):
        if label in breakdown.index:
            r = breakdown.loc[label]
            n = int(r["cells"])
            w = int(r["wins"])
            l = n - w
            cells_n = int(r.get("cells_total", 0))
            pnl = float(r["total_pnl"])
            col.metric(
                label,
                f"{n} trade{'s' if n!=1 else ''}",
                delta=f"{w}W/{l}L · ${pnl:+,.0f}",
                help=f"{cells_n} cells evaluated this window",
            )
        else:
            cells_n = int(cell_counts.get(label, 0))
            col.metric(label, "0 trades", help=f"{cells_n} cells evaluated")

st.divider()

# =============================================================================
# Section 1: The Question
# =============================================================================
st.header("1. What are we trying to answer?", anchor="section-1")

st.markdown(
    """
    > **Can a multi-agent LLM system fed by real satellite radar of drilling
    activity produce directionally-correct long trades for Permian E&P stocks
    in the two weeks before earnings?**

    The system runs on **real public data** across **2019-2024 (6 calendar
    years)**. It evaluates every (firm × fiscal-quarter) **cell** — up to
    10 firms × 4 quarters per year — and decides long / no_trade 14 days
    before each earnings release.

    *Quick glossary:*  **cell** = one (firm × quarter) trade decision.
    **pad** = a real drilling pad in the Permian basin (coordinates from
    FracFocus). Each cell samples **25 representative pads**; a long can fire
    only when the SAR-driven revenue forecast reaches the `modest_beat` band
    versus IBES consensus.
    """
)

st.divider()

# =============================================================================
# Section 2: Real Data
# =============================================================================
st.header("2. What real data does the system actually read?", anchor="section-2")

st.markdown(
    "Every input below is **real public data**. No synthetic substitutes — "
    "if a source were synthetic, we say so explicitly."
)

provenance_df = pd.DataFrame([
    {"Input": "🛰️ Sentinel-1 SAR backscatter (radar pixels, VV only)",
     "Where it comes from": "Microsoft Planetary Computer (free, no auth)",
     "Status": "✅ REAL"},
    {"Input": "📍 Pad coordinates + completion dates",
     "Where it comes from": "FracFocus bulk download — 12,376 Permian permits",
     "Status": "✅ REAL"},
    {"Input": "🛢️ WTI weekly spot price",
     "Where it comes from": "EIA RWTCw.xls (1986-2026)",
     "Status": "✅ REAL"},
    {"Input": "🪨 Permian rig count",
     "Where it comes from": "EIA Drilling Productivity Report",
     "Status": "✅ REAL"},
    {"Input": "📊 Analyst revenue consensus",
     "Where it comes from": "IBES Detail-History (WRDS), REVDATS-corrected",
     "Status": "✅ REAL"},
    {"Input": "📰 News articles for verification",
     "Where it comes from": "GDELT 2.0 DOC API (T-14 enforced)",
     "Status": "✅ REAL"},
    {"Input": "💵 Equity prices for P&L",
     "Where it comes from": "CRSP daily (WRDS) + yfinance Adj Close 2025",
     "Status": "✅ REAL"},
    {"Input": "📅 Earnings dates",
     "Where it comes from": "IBES ANNDATS_ACT (proxy)",
     "Status": "🟡 Real, but proxy"},
    {"Input": "🔧 SAR change-detection thresholds (1.5 dB / 0.5 dB)",
     "Where it comes from": "Ben-David 2021, Glaeser et al. 2020 literature",
     "Status": "🟡 Calibration parameter (not data)"},
])
st.dataframe(provenance_df, hide_index=True, use_container_width=True)

st.divider()

# =============================================================================
# Section 3: The 5 Agents
# =============================================================================
st.header("3. The five-agent pipeline", anchor="section-3")

st.markdown(
    """
    For every cell, the system runs five specialist agents in sequence. Numbers
    that drive trades come from **deterministic Python code**; LLMs only write
    qualitative reasoning.
    """
)

agents_df = pd.DataFrame([
    {"Step": "1. GIS Detection", "Agent": "🛰️ Agent 1",
     "Job": "Read real Sentinel-1 radar pixels at 25 representative pads. "
            "Apply +1.5 dB change-detection rule.",
     "LLM?": "No (pure code)"},
    {"Step": "2. Revenue Forecast", "Agent": "💰 Agent 2",
     "Job": "Compute deterministic forecast = consensus × (1 + 0.10 × drilling_signal). "
            "LLM only writes qualitative outlook.",
     "LLM?": "Yes (annotation only)"},
    {"Step": "3. Consensus Comparison", "Agent": "⚖️ Agent 3",
     "Job": "Compare forecast vs IBES consensus. Classify: strong_beat / modest_beat / "
            "in_line / modest_miss / strong_miss. Cells outside modest_beat range "
            "**short-circuit to no_trade**.",
     "LLM?": "No (pure code)"},
    {"Step": "4. News Verification", "Agent": "📰 Agent 4",
     "Job": "Read GDELT articles up to T-14. If activity already disclosed, "
            "downgrade conviction.",
     "LLM?": "Yes (defensive fallback if fails)"},
    {"Step": "5. Investment Board", "Agent": "🏛️ Agent 5",
     "Job": "Bull/Bear LLM debate moderated by Arbiter. Arbiter assigns conviction "
            "tier; deterministic lookup → size (high=15%, medium=10%, low=5%, none=0%).",
     "LLM?": "Yes (debate only — size in code)"},
])
st.dataframe(agents_df, hide_index=True, use_container_width=True)

st.info(
    "**Why this design?**  An LLM is good at reading news and debating; an LLM is "
    "bad at picking exact numbers. So the *numbers* — forecast, divergence, size — "
    "are computed in Python. The LLM does the natural-language work it's good at."
)

st.divider()

# =============================================================================
# Section 4: Worked Example
# =============================================================================
st.header("4. Walk through one cell end-to-end", anchor="section-4")

st.markdown(
    "Pick a (ticker, quarter) across **any of the six yearly windows (2019-2024)** and "
    "see what each agent produced. "
    "**Recommended demo cell:** `FANG / 2024-Q2` — a 2024 long that lost despite "
    "passing the revenue-signal gate. Try also `OVV / 2023-Q2` (the +15.5% "
    "standout) or `SM / 2020-Q1` (the +91% regime-conditional winner)."
)

if all_cells.empty:
    st.warning("No cell results available.")
else:
    # Quarter first → ticker dropdown filtered to firms actually traded that quarter.
    # Pre-merger / pre-IPO firms (CTRA before 2021-Q4, CRGY before 2022-Q1, PR
    # before 2022-Q4) are SKIPped by the runner, so they don't appear here.
    col1, col2 = st.columns(2)
    quarter_options = sorted(all_cells.fiscal_quarter_end.unique())
    default_quarter_idx = (
        quarter_options.index("2024-06-30") if "2024-06-30" in quarter_options else 0
    )
    fpe = col1.selectbox(
        "Fiscal quarter end", quarter_options, index=default_quarter_idx,
    )

    ticker_options = sorted(
        all_cells[all_cells.fiscal_quarter_end == fpe].ticker.unique()
    )
    default_ticker_idx = (
        ticker_options.index("FANG") if "FANG" in ticker_options else 0
    )
    ticker = col2.selectbox(
        "Ticker (publicly traded with analyst coverage that quarter)",
        ticker_options,
        index=default_ticker_idx,
        help="Tickers in this dropdown are filtered to firms that were public + had "
             "IBES analyst coverage on the fiscal-quarter-end date selected on the left. "
             "CTRA pre-Oct-2021 (pre-merger), CRGY pre-Dec-2021 (pre-IPO), and "
             "PR pre-Sep-2022 (pre-merger) are excluded for the relevant quarters."
    )

    cell_row = all_cells[
        (all_cells.ticker == ticker) & (all_cells.fiscal_quarter_end == fpe)
    ].iloc[0]
    n_eligible = len(ticker_options)
    st.caption(
        f"Window: **{cell_row['window']}**  ·  "
        f"{n_eligible} eligible ticker{'s' if n_eligible!=1 else ''} this quarter"
    )

    # Look up Agent 1 + Agent 3 numbers so the banner can show why
    a1_preview = load_agent_json(ticker, fpe, "agent1") or {}
    a3_preview = load_agent_json(ticker, fpe, "agent3") or {}
    n_active_preview = (
        a1_preview.get("n_newly_active", 0)
        + a1_preview.get("n_continuously_active", 0)
    )
    n_pads_preview = n_active_preview + a1_preview.get("n_idle", 0)
    div_preview = a3_preview.get("divergence_pct")

    # Decision banner — one short line
    if cell_row["decision"] == "long":
        st.success(
            f"📈 **LONG** — {cell_row['conviction_tier']} conviction, "
            f"{cell_row['final_size_pct']:.0%} size  ·  "
            f"{n_active_preview}/{n_pads_preview} pads active  ·  "
            f"divergence {div_preview:+.1f}% vs consensus"
        )
    else:
        err = str(cell_row.get("error") or "")
        if err:
            st.error(f"Cell errored: {err[:140]}")
        elif n_pads_preview:
            st.info(
                f"🚫 **NO TRADE** — only {n_active_preview}/{n_pads_preview} pads active "
                f"({div_preview:+.1f}% divergence; need `modest_beat` or better "
                "for the gate to open)"
            )
        else:
            st.info("🚫 **NO TRADE** — Agent 3 gate fired.")

    # Agent 1 details
    with st.expander("🛰️ **Step 1 — Agent 1 (GIS Detection)**", expanded=True):
        a1 = load_agent_json(ticker, fpe, "agent1")
        if a1 and "error" not in a1:
            cols = st.columns(4)
            cols[0].metric("Newly active pads", a1["n_newly_active"])
            cols[1].metric("Continuously active", a1["n_continuously_active"])
            cols[2].metric("Idle", a1["n_idle"])
            cols[3].metric("Active share", f"{a1['share_active']:.0%}")
            st.caption(
                f"`relative_activity_delta = {a1['relative_activity_delta']:+.2f}` "
                "— activity now vs trailing baseline."
            )
            sar_T = cell_row["decision_date_T"]
            sig = load_sar_aggregate(ticker, fpe, sar_T)
            if sig and "pad_classifications" in sig:
                st.markdown("**Per-pad classifications from real radar pixels:**")
                pads_df = pd.DataFrame(sig["pad_classifications"])
                st.dataframe(pads_df, hide_index=True, use_container_width=True)
                st.caption(
                    f"This cell read **{sig['n_observations_total']} real Sentinel-1 "
                    f"acquisitions** across {sig['n_pads_sampled']} representative pads."
                )
        else:
            st.warning("Agent 1 output not available for this cell.")

    with st.expander("💰 **Step 2 — Agent 2 (Revenue Forecast)**"):
        a2 = load_agent_json(ticker, fpe, "agent2")
        if a2 and "error" not in a2:
            cols = st.columns(2)
            cols[0].metric(
                "Deterministic revenue forecast",
                f"${a2['revenue_forecast_usd']/1e6:,.0f}M"
            )
            comps = a2.get("components", {})
            if comps.get("consensus_anchor_usd"):
                cols[1].metric(
                    "IBES consensus anchor",
                    f"${comps['consensus_anchor_usd']/1e6:,.0f}M"
                )
            if comps.get("drilling_signal_clipped") is not None:
                st.caption(
                    f"`drilling_signal = {comps.get('drilling_signal_clipped'):+.2f}`, "
                    f"`alpha = {comps.get('alpha')}`"
                )
            st.markdown("**LLM qualitative outlook** (does NOT drive the number):")
            st.write(a2.get("outlook_paragraph", "—"))
        else:
            st.caption(
                "Agent 2 did not run — Agent 3 short-circuited the cell, or the "
                "cell errored upstream."
            )

    with st.expander("⚖️ **Step 3 — Agent 3 (Consensus Comparison)**"):
        a3 = load_agent_json(ticker, fpe, "agent3")
        if a3 and "error" not in a3:
            cols = st.columns(3)
            cols[0].metric("Divergence", f"{a3['divergence_pct']:+.2f}%")
            cols[1].metric("Class", a3["divergence_class"])
            cols[2].metric("Confidence", a3["confidence"])
            st.caption(
                "Threshold rule (Python, not LLM): strong_beat > +15% • "
                "modest_beat +5% to +15% • in_line ±5% • modest_miss −5% to −15% • "
                "strong_miss < −15%"
            )
            if a3["divergence_class"] not in ("modest_beat", "strong_beat"):
                st.warning(
                    f"Divergence class is **{a3['divergence_class']}** → "
                    "Agent-3 gate fires → **no_trade**. Agents 4 and 5 do not run."
                )
            else:
                st.success(
                    f"Divergence class is **{a3['divergence_class']}** → cell proceeds "
                    "to Agents 4 and 5."
                )
        else:
            st.caption("No Agent 3 output for this cell.")

    with st.expander("📰 **Step 4 — Agent 4 (News Verification)**"):
        a4 = load_agent_json(ticker, fpe, "agent4")
        if a4 and "error" not in a4:
            cols = st.columns(2)
            cols[0].metric("Articles in window", a4.get("n_articles_in_window", 0))
            cols[1].metric(
                "Already disclosed?",
                "Yes" if a4.get("gdelt_disclosed") else "No"
            )
            reasoning = str(a4.get("reasoning", ""))
            if "fallback" in reasoning.lower():
                st.warning(
                    "⚠️ Agent 4 hit the **defensive fallback path** — the LLM "
                    "returned malformed JSON or rate-limited. Default no-disclosure "
                    "result was used so the cell could proceed."
                )
            st.write(reasoning)
        else:
            st.caption(
                "Agent 4 did not run for this cell (likely Agent-3 short-circuit)."
            )

    with st.expander("🏛️ **Step 5 — Agent 5 (Investment Board: Bull/Bear/Arbiter)**"):
        a5 = load_agent_json(ticker, fpe, "agent5")
        if a5 and "error" not in a5:
            cols = st.columns(3)
            cols[0].metric("Decision", a5.get("decision", "—"))
            cols[1].metric("Conviction", a5.get("conviction_tier", "—"))
            cols[2].metric("Size", f"{a5.get('final_size_pct', 0):.0%}")
            st.markdown("**Bull side:**")
            st.write(a5.get("bull_opinion", {}).get("reasoning_short", "—"))
            st.markdown("**Bear side:**")
            st.write(a5.get("bear_opinion", {}).get("reasoning_short", "—"))
            st.markdown("**Arbiter verdict:**")
            st.write(a5.get("arbiter_reasoning", "—"))
        else:
            st.caption("Agent 5 did not run (Agent-3 short-circuit or cell error).")

st.divider()

# =============================================================================
# Section 5: All Trades 2019-2024
# =============================================================================
st.header("5. Every long trade the system fired (2019-2024)", anchor="section-5")

_MONTH_TO_QUARTER = {3: "Q1", 6: "Q2", 9: "Q3", 12: "Q4"}

if len(all_trades) == 0:
    st.warning("No trades in the multi-window ledger yet.")
else:
    st.caption(
        f"**{len(all_trades)} long trades** across **{all_trades.window.nunique()} windows**. "
        "Each trade enters at T-14 days before the earnings call and exits 2 trading "
        "days strictly after the announcement."
    )

    # Per-trade table — one row per long trade, sorted chronologically
    sorted_t = all_trades.sort_values("entry_date_T").reset_index(drop=True)
    table = pd.DataFrame({
        "#": range(1, len(sorted_t) + 1),
        "Ticker": sorted_t["ticker"],
        "Quarter": [
            f"{_MONTH_TO_QUARTER.get(int(fpe[5:7]), fpe[5:7])} {fpe[:4]}"
            for fpe in sorted_t["fiscal_quarter_end"]
        ],
        "Window": sorted_t["window"],
        "Entry date": sorted_t["entry_date_T"],
        "Exit date": sorted_t["exit_date"],
        "Entry $": sorted_t["entry_price"].map(lambda x: f"${x:,.2f}"),
        "Exit $": sorted_t["exit_price"].map(lambda x: f"${x:,.2f}"),
        "Size %": sorted_t["size_pct"].map(lambda x: f"{x:.0%}"),
        "Gross %": sorted_t["gross_return_pct"].map(lambda x: f"{x*100:+.2f}%"),
        "Net %": sorted_t["net_return_pct"].map(lambda x: f"{x*100:+.2f}%"),
        "$ P&L": sorted_t["net_pnl_usd"].map(lambda x: f"${x:+,.0f}"),
        "Outcome": sorted_t["net_return_pct"].map(
            lambda r: "✅ WIN" if r > 0 else "❌ LOSS"
        ),
    })
    st.dataframe(table, hide_index=True, use_container_width=True)

    # Aggregate metrics (incl. Sharpe) — across the full six-year ledger
    from fin580.inference.pnl import strategy_metrics
    m = strategy_metrics(all_trades)
    st.markdown("**Aggregate metrics across the full 2019-2024 ledger:**")
    mc = st.columns(4)
    mc[0].metric("Hit rate", f"{m['hit_rate']:.0%}")
    mc[1].metric("Mean net return", f"{m['mean_net_return_pct']*100:+.2f}%")
    sharpe_q = m['sharpe_quarterly'] or 0
    mc[2].metric(
        "Sharpe (per-trade)",
        f"{sharpe_q:.2f}",
        help="mean(net_return) / std(net_return) over the trade set. Per-trade "
             "scale, not annualised."
    )
    mc[3].metric("Max drawdown", f"{(m['max_drawdown_pct'] or 0)*100:+.2f}%")

    # Cumulative equity curve across 2019-2024 (reuses sorted_t from the table above)
    sorted_t["cum_growth"] = (1.0 + sorted_t.net_return_pct).cumprod()
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=[sorted_t.iloc[0]["entry_date_T"]] + list(sorted_t.entry_date_T),
        y=[1.0] + list(sorted_t.cum_growth),
        mode="lines+markers", marker_size=10,
        line=dict(color="steelblue", width=3),
        name="Cumulative growth",
        hovertemplate="%{x}<br>Growth: %{y:.4f}<extra></extra>",
    ))
    fig.add_hline(y=1.0, line_dash="dash", line_color="gray")
    fig.update_layout(
        title="Cumulative equity 2019-2024 (real Sentinel-1 SAR Strategy 1)",
        xaxis_title="Entry date",
        yaxis_title="Growth factor (start = 1.0)",
        height=420,
    )
    st.plotly_chart(fig, use_container_width=True)

    # Per-window summary table
    st.markdown("**Per-window summary:**")
    win_summary = all_trades.groupby("window").agg(
        n_trades=("ticker", "count"),
        wins=("net_return_pct", lambda s: (s > 0).sum()),
        hit_rate=("net_return_pct", lambda s: (s > 0).mean() if len(s) else None),
        mean_net_return=("net_return_pct", "mean"),
        total_pnl_usd=("net_pnl_usd", "sum"),
    ).reset_index()
    win_summary["losses"] = win_summary["n_trades"] - win_summary["wins"]
    win_summary["hit_rate"] = win_summary["hit_rate"].apply(
        lambda x: f"{x:.0%}" if pd.notna(x) else "—"
    )
    win_summary["mean_net_return"] = win_summary["mean_net_return"].apply(
        lambda x: f"{x*100:+.2f}%"
    )
    win_summary["total_pnl_usd"] = win_summary["total_pnl_usd"].apply(
        lambda x: f"${x:+,.0f}"
    )
    st.dataframe(
        win_summary[["window", "n_trades", "wins", "losses",
                     "hit_rate", "mean_net_return", "total_pnl_usd"]],
        hide_index=True, use_container_width=True,
    )

st.divider()

# =============================================================================
# Section 6: Comparison
# =============================================================================
st.header("6. Multi-agent system vs passive benchmarks (XES + VOO)",
          anchor="section-6")

st.markdown(
    """
    Two passive buy-and-hold benchmarks over the same backtest window:

    - **XES** — SPDR S&P Oil & Gas Equipment & Services ETF (sector benchmark)
    - **VOO** — Vanguard S&P 500 ETF (broad market benchmark)

    Both start at \$1M on the day of the system's first trade entry and hold
    through the day of the system's last trade exit (always 100% deployed).
    The system holds **cash at 0% between trades** and only the position
    size during each trade — it is in the market roughly 10% of trading
    days. A direct cumulative-P&L comparison therefore gives the passive
    benchmarks ~6× more time-in-market than the system. The three panels
    below report the comparison in three different ways:

    1. **Absolute cumulative P&L** (with cash leg) — the chart immediately below.
       Honest "investable strategy" view, but the system loses against
       always-deployed benchmarks during long out-of-market stretches.
    2. **Risk-adjusted (annualized Sharpe)** — same units, accounts for
       time-in-market implicitly via the variance.
    3. **Return on capital deployed (annualized)** — only counts the days
       the system actually had a position. Answers "when actually trading,
       what does the system earn per unit of risk-on capital?"
    """
)

bench = load_benchmark_prices()
if bench.empty or len(all_trades) == 0:
    st.warning(
        "Benchmark prices or trade ledger missing. Run "
        "`python scripts/fetch_benchmarks.py` to refresh, or check that "
        "`phase1/output/benchmark_prices.csv` exists."
    )
else:
    # Establish the window: from first entry to last exit
    start = pd.to_datetime(all_trades["entry_date_T"]).min()
    end = pd.to_datetime(all_trades["exit_date"]).max()

    win = bench[(bench["date"] >= start) & (bench["date"] <= end)].copy().reset_index(drop=True)
    if win.empty:
        st.warning(f"No benchmark data in window {start.date()} → {end.date()}.")
    else:
        # Normalize benchmarks to $1M starting capital
        START_CAPITAL = 1_000_000
        win["XES_value"] = START_CAPITAL * win["XES"] / win["XES"].iloc[0]
        win["VOO_value"] = START_CAPITAL * win["VOO"] / win["VOO"].iloc[0]

        # System equity: cumulative net P&L applied as each trade exits
        trades_by_exit = all_trades.copy()
        trades_by_exit["exit_date_dt"] = pd.to_datetime(trades_by_exit["exit_date"])
        trades_by_exit = trades_by_exit.sort_values("exit_date_dt")

        sys_values = []
        cum_pnl = 0.0
        for d in win["date"]:
            # Sum net P&L from all trades whose exit_date <= d
            cum_pnl = float(
                trades_by_exit[trades_by_exit["exit_date_dt"] <= d]["net_pnl_usd"].sum()
            )
            sys_values.append(START_CAPITAL + cum_pnl)
        win["System_value"] = sys_values

        # Compute headline metrics
        def metrics(values: pd.Series, dates: pd.Series) -> dict:
            v = values.values
            ret_total = v[-1] / v[0] - 1.0
            n_years = (dates.iloc[-1] - dates.iloc[0]).days / 365.25
            ret_ann = (v[-1] / v[0]) ** (1 / n_years) - 1.0 if n_years > 0 else 0.0
            daily_ret = pd.Series(v).pct_change().dropna()
            sharpe = (
                daily_ret.mean() / daily_ret.std() * (252 ** 0.5)
                if daily_ret.std() > 0 else 0.0
            )
            roll_max = pd.Series(v).cummax()
            dd = (pd.Series(v) - roll_max) / roll_max
            max_dd = dd.min()
            return {
                "Total return": f"{ret_total:+.2%}",
                "Annualized return": f"{ret_ann:+.2%}",
                "Sharpe (daily, ann.)": f"{sharpe:.2f}",
                "Max drawdown": f"{max_dd:.2%}",
                "End value ($1M start)": f"${v[-1]:,.0f}",
            }

        sys_m = metrics(win["System_value"], win["date"])
        xes_m = metrics(win["XES_value"], win["date"])
        voo_m = metrics(win["VOO_value"], win["date"])

        summary_df = pd.DataFrame(
            [
                {"Strategy": "Multi-agent (real SAR) — Strategy 1", **sys_m},
                {"Strategy": "XES buy-and-hold (oil services)", **xes_m},
                {"Strategy": "VOO buy-and-hold (S&P 500)", **voo_m},
            ]
        )
        st.dataframe(summary_df, hide_index=True, use_container_width=True)

        # Equity curve plot
        fig = go.Figure()
        fig.add_trace(go.Scatter(
            x=win["date"], y=win["System_value"],
            mode="lines", name="Multi-agent (real SAR)",
            line=dict(color="steelblue", width=3),
            hovertemplate="%{x|%Y-%m-%d}<br>System: $%{y:,.0f}<extra></extra>",
        ))
        fig.add_trace(go.Scatter(
            x=win["date"], y=win["XES_value"],
            mode="lines", name="XES (oil services)",
            line=dict(color="darkorange", width=2, dash="dash"),
            hovertemplate="%{x|%Y-%m-%d}<br>XES: $%{y:,.0f}<extra></extra>",
        ))
        fig.add_trace(go.Scatter(
            x=win["date"], y=win["VOO_value"],
            mode="lines", name="VOO (S&P 500)",
            line=dict(color="seagreen", width=2, dash="dot"),
            hovertemplate="%{x|%Y-%m-%d}<br>VOO: $%{y:,.0f}<extra></extra>",
        ))
        fig.add_hline(y=START_CAPITAL, line_dash="dot", line_color="gray",
                      annotation_text="$1M start", annotation_position="bottom right")
        fig.update_layout(
            title=f"Equity curves: $1M starting capital, "
                  f"{start.strftime('%Y-%m-%d')} to {end.strftime('%Y-%m-%d')}",
            xaxis_title="Date",
            yaxis_title="Portfolio value (USD)",
            height=480,
            hovermode="x unified",
            yaxis=dict(tickformat="$,.0f"),
        )
        st.plotly_chart(fig, use_container_width=True)

        # ---------------------------------------------------------------
        # Fair-comparison panel: time-in-market + return on capital deployed
        # ---------------------------------------------------------------
        st.markdown("### Fair-comparison metrics")

        # Time-in-market fraction (trading days with at least one open position)
        all_dates = pd.to_datetime(win["date"])
        trades_dt = all_trades.copy()
        trades_dt["entry_dt"] = pd.to_datetime(trades_dt["entry_date_T"])
        trades_dt["exit_dt"] = pd.to_datetime(trades_dt["exit_date"])
        in_market_mask = pd.Series(False, index=all_dates.index)
        for _, tr in trades_dt.iterrows():
            in_market_mask |= (all_dates >= tr["entry_dt"]) & (all_dates <= tr["exit_dt"])
        n_in_market = int(in_market_mask.sum())
        n_total_days = len(all_dates)
        time_in_market_pct = (n_in_market / n_total_days) if n_total_days else 0.0

        # Capital-years deployed = sum across trades of (size_pct × holding_years)
        trades_dt["holding_calendar_days"] = (
            trades_dt["exit_dt"] - trades_dt["entry_dt"]
        ).dt.days
        trades_dt["capital_years_deployed"] = (
            trades_dt["size_pct"] * trades_dt["holding_calendar_days"] / 365.25
        )
        total_capital_years = float(trades_dt["capital_years_deployed"].sum())
        total_pnl = float(trades_dt["net_pnl_usd"].sum())
        rcd_annualized = (
            total_pnl / (total_capital_years * START_CAPITAL)
            if total_capital_years > 0 else 0.0
        )

        # Benchmark annualized returns (XES, VOO) — same window
        n_years = (win["date"].iloc[-1] - win["date"].iloc[0]).days / 365.25
        xes_total = win["XES_value"].iloc[-1] / win["XES_value"].iloc[0] - 1.0
        voo_total = win["VOO_value"].iloc[-1] / win["VOO_value"].iloc[0] - 1.0
        xes_ann = (
            (1.0 + xes_total) ** (1 / n_years) - 1.0 if n_years > 0 else 0.0
        )
        voo_ann = (
            (1.0 + voo_total) ** (1 / n_years) - 1.0 if n_years > 0 else 0.0
        )

        fc_cols = st.columns(4)
        fc_cols[0].metric(
            "Time in market",
            f"{time_in_market_pct:.1%}",
            help=f"{n_in_market} of {n_total_days} trading days had at least "
                 "one open position. Cash held the rest of the time."
        )
        fc_cols[1].metric(
            "Capital-years deployed",
            f"{total_capital_years:.2f}",
            help=f"Σ (size_pct × holding_years) across all {len(all_trades)} "
                 f"trades. Equivalent to holding {total_capital_years:.2f} years "
                 "at $1M full-size exposure."
        )
        fc_cols[2].metric(
            "Return on capital deployed (ann.)",
            f"{rcd_annualized:+.1%}",
            help="Total $ P&L divided by capital-years deployed. The system's "
                 "return rate on the days it was actually in the market, "
                 "annualized. Compare to XES/VOO annualized return below."
        )
        fc_cols[3].metric(
            "Window length",
            f"{n_years:.2f} yrs",
            help=f"From {win['date'].iloc[0].date()} to "
                 f"{win['date'].iloc[-1].date()}."
        )

        # Side-by-side strategy comparison: total + annualized + Sharpe
        fc_summary = pd.DataFrame([
            {
                "Strategy": "System (multi-agent, when deployed)",
                "Time in market": f"{time_in_market_pct:.1%}",
                "Total return on $1M (cash leg)": (
                    f"{(win['System_value'].iloc[-1]/START_CAPITAL - 1):+.2%}"
                ),
                "Annualized return on capital deployed": f"{rcd_annualized:+.2%}",
                "Annualized Sharpe (daily)": sys_m["Sharpe (daily, ann.)"],
            },
            {
                "Strategy": "XES (always deployed)",
                "Time in market": "100.0%",
                "Total return on $1M (cash leg)": f"{xes_total:+.2%}",
                "Annualized return on capital deployed": f"{xes_ann:+.2%}",
                "Annualized Sharpe (daily)": xes_m["Sharpe (daily, ann.)"],
            },
            {
                "Strategy": "VOO (always deployed)",
                "Time in market": "100.0%",
                "Total return on $1M (cash leg)": f"{voo_total:+.2%}",
                "Annualized return on capital deployed": f"{voo_ann:+.2%}",
                "Annualized Sharpe (daily)": voo_m["Sharpe (daily, ann.)"],
            },
        ])
        st.dataframe(fc_summary, hide_index=True, use_container_width=True)

        st.info(
            f"**How to read these three columns together.** "
            f"On a cash-leg basis the system makes "
            f"{(win['System_value'].iloc[-1]/START_CAPITAL - 1):+.1%} vs "
            f"VOO's {voo_total:+.1%} — VOO wins because it's deployed 10× as "
            f"long. But on a per-unit-of-deployed-capital basis the system "
            f"earns **{rcd_annualized:+.1%}** annualized vs VOO's "
            f"**{voo_ann:+.1%}** and XES's **{xes_ann:+.1%}** — a meaningful "
            f"per-trade signal that gets diluted by long out-of-market stretches. "
            f"The Sharpe ratios anchor a risk-adjusted comparison: the system's "
            f"low Sharpe (because cash days inflate the denominator and shrink "
            f"the numerator) is the cleanest single-number summary of the "
            f"asymmetry."
        )

        st.markdown(
            f"""
            **Reading this chart (absolute, cash-leg cumulative):**

            - **Multi-agent system** is mostly flat — it holds cash between trades
              ({time_in_market_pct:.0%} time in market). The visible jumps are
              the 23 trade exits.
            - **VOO** crushes both — the broad market roughly tripled over this window.
              An honest Permian-equity strategy needs to either (a) generate enough
              alpha to beat VOO net of risk, or (b) provide a diversification benefit
              not measurable from total return alone.
            - **XES is a tough sector benchmark.** Oil services have *lost* ~13% over
              this window. If our system can match or beat XES, that's a real
              sector-relative result; matching VOO would require dramatically more
              persistent signal than the system currently produces.
            - The headline +\$6,634 is small in magnitude (+0.66% of capital). No
              single trade dominates: largest single contributor is SM 2021-Q3
              (+\$24K). The aggregate is statistically indistinguishable from zero
              and well within the 30 bps round-trip cost band.
            """
        )

st.divider()

# =============================================================================
# Section 7: Honest Limitations
# =============================================================================
st.header("7. What we honestly cannot claim", anchor="section-7")

_n_trades_6y = len(all_trades) if len(all_trades) else 0
_hit_rate_6y = (
    (all_trades.net_return_pct > 0).mean() if _n_trades_6y else None
)
_mean_ret_6y = all_trades.net_return_pct.mean() if _n_trades_6y else None

st.warning(
    f"**The most honest framing (full 2019-2024 window):** "
    f"With **n = {_n_trades_6y} trades** across 2019-2024, the hit rate is "
    f"**{(_hit_rate_6y or 0)*100:.1f}%** and mean net return is "
    f"**{(_mean_ret_6y or 0)*100:+.2f}%**. The firm-clustered bootstrap p-value "
    f"vs H0 = 50% is **0.328** — we **cannot reject the coin-flip null**. "
    f"The 95% CI on hit rate is [39.5%, 65.1%] and the firm-clustered 95% CI on "
    f"mean return [-1.83%, +1.53%] straddles zero. No single trade dominates the "
    f"aggregate; the largest single contributor is SM 2021-Q3 (+\\$24K)."
)

st.markdown(
    """
    **Why is the sample size what it is?**

    1. **Most cells short-circuit** — the Agent 3 gate only opens on `modest_beat` /
       `strong_beat` divergence (±5% boundary). Across all years, ~25% of cells
       cleared the gate; the rest correctly produced `no_trade`.
    2. **Real data only** — no synthetic substitutes. Real Sentinel-1 SAR ingestion
       is bandwidth-limited via cloud-optimised GeoTIFF range-reads from Microsoft
       Planetary Computer (free, no auth).
    3. **25 pads per firm-quarter** — deduplicated by `(pad_id, rounded coords)`.
       Increasing toward the operator's full FracFocus history is documented as
       future work (paper §13).

    **2021 over-firing is the dominant structural pattern.** The system fires
    **16 long trades in 2021** (vs 2-9 in every other year), of which **13
    clip at `drilling_signal = +1.0`** and reach an identical +10.0%
    divergence number. The clip is functioning as designed but collapses signal
    differentiation across the post-COVID recovery cohort: the gate cannot
    distinguish a modest recovery from an explosive one when trailing baselines
    are depressed by a prior dislocation. Disclosed in paper §12.4 rather than
    tuned post-hoc.

    **The pre-registered WTI stress veto** would block one 2020-Q1 entry (OVV,
    +\$16,900), shifting the aggregate from +\$13,432 to -\$3,468. The
    qualitative finding "macro-stress veto removes a gain rather than a loss"
    survives at smaller magnitude than earlier reported.

    **What we *can* claim is mechanical:** the α=0 ablation and no-satellite
    ablation both produce **zero long entries** by construction. So whatever
    trade-firing signal the system did produce 2019-2024 is mechanically traceable
    to the satellite input — not to the LLM scaffolding.
    """
)

# H1 / H2 inference numbers
if ev_pack:
    h1 = ev_pack.get("primary_test_H1", {})
    h2 = ev_pack.get("secondary_test_H2", {})
    cols = st.columns(2)
    with cols[0]:
        st.markdown("**H1: hit rate > 50%**")
        st.write(f"- Bootstrap p-value: **{h1.get('p_value_one_sided')}**")
        st.write(f"- 95% CI: {h1.get('ci_95')}")
        st.write(f"- Reject H0 = 50%: **{h1.get('reject_50')}**")
    with cols[1]:
        st.markdown("**H2: S1 hit rate > S3 by 3pp**")
        st.write(f"- Observed gap: **+{h2.get('obs_diff', 0)*100:.1f}pp**")
        st.write(f"- Bootstrap p-value: **{h2.get('p_one_sided_diff_le_threshold')}**")
        st.write(f"- Reject H0: **{h2.get('reject_null_at_5pct')}**")

st.divider()

# =============================================================================
# Footer
# =============================================================================
st.caption(
    "FIN 580 — Spring 2026 — Vincent N. W. — "
    "Multi-Agent Permian Trading System with Real Sentinel-1 SAR (2019-2024 window). "
    "Reproducibility (per year): "
    "`FIN580_SAR_MODE=real_sentinel1 FIN580_SAR_PADS_PER_OP=25 "
    "python -m fin580.backtest.runner "
    "--strategy 1 --window <YYYY>Q1-<YYYY>Q4 --cm-label target --run-suffix realsar`"
)
